{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e9f8877",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "def gerar_base_colaboradores(n_colaboradores: int = 2500,\n",
    "                             seed: int = 42) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Gera base simulada de colaboradores com viés estratégico\n",
    "    voltado para análise de turnover e desigualdade organizacional.\n",
    "\n",
    "    Parâmetros:\n",
    "    -----------\n",
    "    n_colaboradores : int\n",
    "        Quantidade total de colaboradores simulados.\n",
    "    seed : int\n",
    "        Semente para reprodutibilidade.\n",
    "\n",
    "    Retorno:\n",
    "    --------\n",
    "    pd.DataFrame\n",
    "        DataFrame com dados simulados.\n",
    "    \"\"\"\n",
    "\n",
    "    # Definindo seed para garantir reprodutibilidade\n",
    "    np.random.seed(seed)\n",
    "\n",
    "    # ================================\n",
    "    # Estrutura organizacional\n",
    "    # ================================\n",
    "\n",
    "    areas = [\n",
    "        \"Comercial\",\n",
    "        \"Tecnologia\",\n",
    "        \"Risco_&_Compliance\",\n",
    "        \"Credito\",\n",
    "        \"Produtos_Digitais\",\n",
    "        \"Backoffice\"\n",
    "    ]\n",
    "\n",
    "    distribuicao_areas = [0.30, 0.20, 0.15, 0.15, 0.10, 0.10]\n",
    "\n",
    "    area = np.random.choice(areas,\n",
    "                            size=n_colaboradores,\n",
    "                            p=distribuicao_areas)\n",
    "\n",
    "    # ================================\n",
    "    # Dados demográficos\n",
    "    # ================================\n",
    "\n",
    "    idade = np.random.normal(loc=35, scale=8, size=n_colaboradores).astype(int)\n",
    "    idade = np.clip(idade, 21, 60)\n",
    "\n",
    "    genero = np.random.choice([\"Masculino\", \"Feminino\"],\n",
    "                              size=n_colaboradores,\n",
    "                              p=[0.55, 0.45])\n",
    "\n",
    "    escolaridade = np.random.choice(\n",
    "        [\"Graduacao\", \"Pos_Graduacao\", \"MBA\", \"Mestrado\"],\n",
    "        size=n_colaboradores,\n",
    "        p=[0.40, 0.35, 0.20, 0.05]\n",
    "    )\n",
    "\n",
    "    # ================================\n",
    "    # Dados organizacionais\n",
    "    # ================================\n",
    "\n",
    "    nivel_cargo = np.random.choice(\n",
    "        [\"Junior\", \"Pleno\", \"Senior\", \"Coordenador\"],\n",
    "        size=n_colaboradores,\n",
    "        p=[0.35, 0.35, 0.20, 0.10]\n",
    "    )\n",
    "\n",
    "    tempo_empresa = np.random.exponential(scale=4,\n",
    "                                          size=n_colaboradores)\n",
    "    tempo_empresa = np.round(tempo_empresa, 1)\n",
    "    tempo_empresa = np.clip(tempo_empresa, 0.1, 20)\n",
    "\n",
    "    # ================================\n",
    "    # Salário por área\n",
    "    # ================================\n",
    "\n",
    "    salario_base_area = {\n",
    "        \"Comercial\": 5000,\n",
    "        \"Tecnologia\": 8000,\n",
    "        \"Risco_&_Compliance\": 7500,\n",
    "        \"Credito\": 6500,\n",
    "        \"Produtos_Digitais\": 7800,\n",
    "        \"Backoffice\": 4500\n",
    "    }\n",
    "\n",
    "    salario = np.array([\n",
    "        np.random.normal(loc=salario_base_area[a], scale=1500)\n",
    "        for a in area\n",
    "    ])\n",
    "\n",
    "    salario = np.round(np.clip(salario, 2500, 30000), 2)\n",
    "\n",
    "    # ================================\n",
    "    # Referência salarial de mercado\n",
    "    # Tecnologia com maior gap\n",
    "    # ================================\n",
    "\n",
    "    referencia_mercado = salario * np.random.normal(loc=1.05,\n",
    "                                                    scale=0.05,\n",
    "                                                    size=n_colaboradores)\n",
    "\n",
    "    gap_salarial_pct = ((salario - referencia_mercado) /\n",
    "                        referencia_mercado) * 100\n",
    "\n",
    "    # ================================\n",
    "    # Engajamento (Comercial menor)\n",
    "    # ================================\n",
    "\n",
    "    engajamento = np.array([\n",
    "        np.random.normal(3.2, 0.7) if a == \"Comercial\"\n",
    "        else np.random.normal(3.8, 0.6)\n",
    "        for a in area\n",
    "    ])\n",
    "\n",
    "    engajamento = np.clip(engajamento, 1, 5)\n",
    "    engajamento = np.round(engajamento, 1)\n",
    "\n",
    "    # ================================\n",
    "    # Performance\n",
    "    # ================================\n",
    "\n",
    "    performance = np.random.normal(3.5, 0.7, n_colaboradores)\n",
    "    performance = np.clip(performance, 1, 5)\n",
    "    performance = np.round(performance, 1)\n",
    "\n",
    "    # ================================\n",
    "    # Promoção com possível viés\n",
    "    # ================================\n",
    "\n",
    "    promocao_2anos = []\n",
    "\n",
    "    for i in range(n_colaboradores):\n",
    "        prob = 0.15\n",
    "\n",
    "        if genero[i] == \"Masculino\":\n",
    "            prob += 0.05  # viés intencional\n",
    "\n",
    "        promocao_2anos.append(np.random.binomial(1, prob))\n",
    "\n",
    "    # ================================\n",
    "    # Turnover voluntário estratégico\n",
    "    # ================================\n",
    "\n",
    "    turnover = []\n",
    "\n",
    "    for i in range(n_colaboradores):\n",
    "\n",
    "        prob = 0.08  # base\n",
    "\n",
    "        if area[i] in [\"Comercial\", \"Tecnologia\"]:\n",
    "            prob += 0.07\n",
    "\n",
    "        if gap_salarial_pct[i] < -5:\n",
    "            prob += 0.05\n",
    "\n",
    "        if engajamento[i] < 3:\n",
    "            prob += 0.05\n",
    "\n",
    "        turnover.append(np.random.binomial(1, prob))\n",
    "\n",
    "    # ================================\n",
    "    # Construção do DataFrame\n",
    "    # ================================\n",
    "\n",
    "    df = pd.DataFrame({\n",
    "        \"id_colaborador\": range(1, n_colaboradores + 1),\n",
    "        \"area\": area,\n",
    "        \"idade\": idade,\n",
    "        \"genero\": genero,\n",
    "        \"escolaridade\": escolaridade,\n",
    "        \"nivel_cargo\": nivel_cargo,\n",
    "        \"tempo_empresa_anos\": tempo_empresa,\n",
    "        \"salario\": salario,\n",
    "        \"referencia_mercado\": np.round(referencia_mercado, 2),\n",
    "        \"gap_salarial_pct\": np.round(gap_salarial_pct, 2),\n",
    "        \"engajamento\": engajamento,\n",
    "        \"performance\": performance,\n",
    "        \"promocao_ultimos_2_anos\": promocao_2anos,\n",
    "        \"turnover_voluntario\": turnover\n",
    "    })\n",
    "\n",
    "    return df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
